-- MySQL Script generated by MySQL Workbench (modified)
-- mar. 18 juil. 2017 21:37:32 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema GestionTableConv
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GestionTableConv` ;

-- -----------------------------------------------------
-- Schema GestionTableConv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestionTableConv` DEFAULT CHARACTER SET latin1 ;
USE `GestionTableConv` ;

-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Joueur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Joueur` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Joueur` (
  `id_Joueur` INT NOT NULL AUTO_INCREMENT,
  `Jou_FirstName` VARCHAR(16) NOT NULL,
  `Jou_LastName` VARCHAR(16) NOT NULL,
  `Jou_Mail` VARCHAR(100) NULL,
  `Jou_TelNumber` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Joueur`))
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Responsabilite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Responsabilite` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Responsabilite` (
  `id_Responsabilite` INT NOT NULL AUTO_INCREMENT,
  `Res_Name` VARCHAR(45) NOT NULL DEFAULT 'Responsabilité non définie',
  PRIMARY KEY (`id_Responsabilite`))
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Association`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Association` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Association` (
  `id_Association` INT NOT NULL AUTO_INCREMENT,
  `Ass_Name` VARCHAR(45) NOT NULL DEFAULT 'Association non définie',
  PRIMARY KEY (`id_Association`))
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Organisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Organisateur` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Organisateur` (
  `id_Organisateur` INT NOT NULL AUTO_INCREMENT,
  `Org_FirstName` VARCHAR(16) NOT NULL,
  `Org_LastName` VARCHAR(16) NOT NULL,
  `Org_Nickname` VARCHAR(16) NULL,
  `Org_TelNumber` VARCHAR(10) NOT NULL,
  `Org_Password` VARCHAR(45) NOT NULL,
  `id_Responsabilite` INT NOT NULL,
  `id_Association` INT NOT NULL,
  PRIMARY KEY (`id_Organisateur`),
  INDEX `FK_Res_Org_idx` (`id_Responsabilite` ASC),
  INDEX `FK_ORG_ASS_idx` (`id_Association` ASC),
  CONSTRAINT `FK_ORG_RES`
    FOREIGN KEY (`id_Responsabilite`)
    REFERENCES `GestionTableConv`.`T_Responsabilite` (`id_Responsabilite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ORG_ASS`
    FOREIGN KEY (`id_Association`)
    REFERENCES `GestionTableConv`.`T_Association` (`id_Association`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Editeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Editeur` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Editeur` (
  `id_Editeur` INT NOT NULL AUTO_INCREMENT,
  `Edi_Name` VARCHAR(45) NOT NULL,
  `Edi_Website` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Editeur`))
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Systeme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Systeme` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Systeme` (
  `id_Systeme` INT NOT NULL AUTO_INCREMENT,
  `Sys_Name` VARCHAR(45) NOT NULL,
  `Sys_Quatrieme` VARCHAR(45) NOT NULL,
  `Sys_Description` VARCHAR(45) NOT NULL,
  `Sys_Website` VARCHAR(45) NOT NULL,
  `Sys_id_Editeur` INT NULL,
  PRIMARY KEY (`id_Systeme`),
  INDEX `fk_T_Systeme_1_idx` (`Sys_id_Editeur` ASC),
  CONSTRAINT `FK_Edi_Sys`
    FOREIGN KEY (`Sys_id_Editeur`)
    REFERENCES `GestionTableConv`.`T_Editeur` (`id_Editeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_MotCle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_MotCle` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_MotCle` (
  `id_MotCle` INT NOT NULL AUTO_INCREMENT,
  `MCl_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_MotCle`))
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Theme` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Theme` (
  `id_Systeme` INT NOT NULL,
  `id_MotCle` INT NOT NULL,
  INDEX `FK_Sys_The_idx` (`id_Systeme` ASC),
  PRIMARY KEY (`id_Systeme`, `id_MotCle`),
  INDEX `FK_MCl_The_idx` (`id_MotCle` ASC),
  CONSTRAINT `FK_Sys_The`
    FOREIGN KEY (`id_Systeme`)
    REFERENCES `GestionTableConv`.`T_Systeme` (`id_Systeme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MCl_The`
    FOREIGN KEY (`id_MotCle`)
    REFERENCES `GestionTableConv`.`T_MotCle` (`id_MotCle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Scenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Scenario` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Scenario` (
  `id_Scenario` INT NOT NULL AUTO_INCREMENT,
  `Sce_Name` VARCHAR(45) NULL,
  `Sce_NumberOfPlayers` INT NOT NULL,
  `Sce_Duration` INT NOT NULL,
  `Sce_Description` VARCHAR(45) NULL,
  `id_Organisateur` INT NOT NULL,
  `id_Systeme` INT NOT NULL,
  PRIMARY KEY (`id_Scenario`),
  INDEX `FK_ORG_SCE_idx` (`id_Organisateur` ASC),
  INDEX `FK_ORG_SYS_idx` (`id_Systeme` ASC),
  CONSTRAINT `FK_ORG_SCE`
    FOREIGN KEY (`id_Organisateur`)
    REFERENCES `GestionTableConv`.`T_Organisateur` (`id_Responsabilite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ORG_SYS`
    FOREIGN KEY (`id_Systeme`)
    REFERENCES `GestionTableConv`.`T_Systeme` (`id_Systeme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Convention`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Convention` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Convention` (
  `id_Convention` INT NOT NULL AUTO_INCREMENT,
  `Con_Name` VARCHAR(45) NOT NULL,
  `Con_TableQuantity` INT NOT NULL,
  `Con_StartDate` DATETIME NOT NULL,
  `Con_EndDate` DATETIME NOT NULL,
  PRIMARY KEY (`id_Convention`))
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Disponibilite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Disponibilite` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Disponibilite` (
  `id_Disponibilite` INT NOT NULL AUTO_INCREMENT,
  `Dis_Schedule` DATE NOT NULL,
  `Dis_TableNumber` INT NULL,
  `id_Convention` INT NOT NULL,
  `id_Scenario` INT NOT NULL,
  PRIMARY KEY (`id_Disponibilite`),
  INDEX `FK_DIS_SCE_idx` (`id_Scenario` ASC),
  INDEX `FK_DIS_CON_idx` (`id_Convention` ASC),
  CONSTRAINT `FK_DIS_CON`
    FOREIGN KEY (`id_Convention`)
    REFERENCES `GestionTableConv`.`T_Convention` (`id_Convention`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DIS_SCE`
    FOREIGN KEY (`id_Scenario`)
    REFERENCES `GestionTableConv`.`T_Scenario` (`id_Scenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Aria;


-- -----------------------------------------------------
-- Table `GestionTableConv`.`T_Partie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GestionTableConv`.`T_Partie` ;

CREATE TABLE IF NOT EXISTS `GestionTableConv`.`T_Partie` (
  `id_Disponibilite` INT NOT NULL,
  `id_Joueur` INT NOT NULL,
  INDEX `FK_DIS_PAR_idx` (`id_Disponibilite` ASC),
  INDEX `FK_JOU_PAR_idx` (`id_Joueur` ASC),
  PRIMARY KEY (`id_Disponibilite`, `id_Joueur`),
  CONSTRAINT `FK_DIS_PAR`
    FOREIGN KEY (`id_Disponibilite`)
    REFERENCES `GestionTableConv`.`T_Disponibilite` (`id_Disponibilite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_JOU_PAR`
    FOREIGN KEY (`id_Joueur`)
    REFERENCES `GestionTableConv`.`T_Joueur` (`id_Joueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = Aria;
